########################################################
##   与application.properties效果一致，写法不一样
########################################################
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shaizi?useSSL=false
#    username: rtrc
#    password: 2wsx#EDC

spring:
  redis:
    host: 127.0.0.1
    port: 6379
#    password: 123456
mybatis:
  typeAliasesPackage: com.test.sz.model
  mapperLocations: classpath:mapper/*.xml