CREATE TABLE T_S_INFO
(
  STOCK_CODE       VARCHAR(12),
  STOCK_NAME       VARCHAR(32),
  TODAY_PRICE      DECIMAL(18,2),
  YESTERDAY_PRICE  DECIMAL(18,2),
  DEALED_DATE      VARCHAR(23),
  JIN_KAI          DECIMAL(18,2),
  DEALED_CJE       DECIMAL(25,2),
  DEALED_CJL       DECIMAL(25,2),
  TOTAL_SHI_ZHI    DECIMAL(20,2),
  LIU_TONG_SHI_ZHI DECIMAL(20,2),
  WAI_PAN          DECIMAL(25,2),
  NEI_PAN          DECIMAL(20,2),
  BUY1             DECIMAL(18,2),
  BUY2             DECIMAL(18,2),
  BUY3             DECIMAL(18,2),
  BUY4             DECIMAL(18,2),
  BUY5             DECIMAL(18,2),
  BUY1_AMOUNT      DECIMAL(20,2),
  BUY2_AMOUNT      DECIMAL(20,2),
  BUY3_AMOUNT      DECIMAL(20,2),
  BUY4_AMOUNT      DECIMAL(20,2),
  BUY5_AMOUNT      DECIMAL(20,2),
  SELL1            DECIMAL(28,2),
  SELL2            DECIMAL(18,2),
  SELL3            DECIMAL(18,2),
  SELL4            DECIMAL(18,2),
  SELL5            DECIMAL(18,2),
  SELL1_AMOUNT     DECIMAL(20,2),
  SELL2_AMOUNT     DECIMAL(20,2),
  SELL3_AMOUNT     DECIMAL(20,2),
  SELL4_AMOUNT     DECIMAL(20,2),
  SELL5_AMOUNT     DECIMAL(20,2),
  ZHANG_DIE        DECIMAL(18,2),
  ZHANG_FU_LV      DECIMAL(20,2),
  HUAN_SHOU_LV     DECIMAL(20,2),
  SHI_YIN_LV       DECIMAL(20,2),
  ZUI_GAO          DECIMAL(18,2),
  ZUI_DI           DECIMAL(18,2),
  ZHEN_FU          DECIMAL(18,2),
  SHI_JIN_LV       DECIMAL(18,2),
  ZHANG_TING_JIA   DECIMAL(18,2),
  DIE_TING_JIA     DECIMAL(18,2),
  DETAIL_TIME      VARCHAR(20)
);

CREATE TABLE T_S_DATE
(
  DATE_ID  int auto_increment primary key,
  DEAL_DATE VARCHAR(23),
  MARKET    VARCHAR(5)
);

CREATE TABLE T_S_TOP5
(
  STOCK_CODE      VARCHAR(8),
  CONTINUE_DAYS   VARCHAR(3),
  DIE_FU          DECIMAL(18,2),
  NEXT_DAY_DIE_FU DECIMAL(18,2),
  STATISTIC_DATE  VARCHAR(23),
  KAI_PAN         DECIMAL(18,2),
  STOCK_NAME      VARCHAR(32),
  ZUO_SHOU        DECIMAL(18,2),
  THE_WAY         VARCHAR(10),
  KDJ             DECIMAL(18,2),
  GAO_KAI         DECIMAL(18,2),
  THIRD_DAY       DECIMAL(18,2),
  TD_RATE         DECIMAL(18,2),
  BUY_PRICE       DECIMAL(18,2),
  SELL_PRICE      DECIMAL(18,2)
);
